apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: nextjs
spec:
  type: NodePort   # good for Minikube; alternatively ClusterIP + minikube service
  selector:
    app: nextjs
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30030

